void LPT(init)(lpt *code, uint8_t perm);
uint64_t LPT(tointeger)(lpt code);
lpt LPT(frominteger)(uint64_t code);
int LPT(level)(lpt code);
int LPT(simplex_level)(lpt code);
int LPT(orthant_level)(lpt code);
lpt LPT(child)(lpt code, int zo);
bool LPT(is_child0)(lpt code); 
lpt LPT(parent)(lpt code); 
int LPT(orientation)(lpt code);
int LPT(neighbor_bd)(lpt code, int i, lpt *r);
bool LPT(neighbor)(lpt code, int i, lpt *r);
void LPT(simplex)(lpt code, double *s);
void LPT(print_simplex)(lpt code);
LPT(tree) * LPT(tree_new)(size_t buckets);
void LPT(tree_free)(LPT(tree) *tree);
void LPT(tree_print_stats)(LPT(tree) *tree);
void LPT(tree_compat_bisect)(LPT(tree) *tree, lpt code, void (*subdivided)(lpt,void*), void (*new_vertex)(int,double *,void*), void *udata);
bool LPT(tree_is_leaf)(LPT(tree) *tree, lpt code);
void LPT(tree_visit_leafs)(LPT(tree) *tree, void (*visit)(lpt,void*), void *udata);
void LPT(tree_search_all)(LPT(tree) *tree, double * p, void (*visit)(lpt,void*), void *udata);