include ../make.inc

all:
	@echo "This library is pure Lua, so there is no need to compile it. Just run 'make install' to copy the .lua file to the Lua library directory."

install:
	cp ply.lua $(LIBDIR)

clean:
	rm -f *.ply
